# Generated by Django 4.0.1 on 2022-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'major',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('registered_date', models.DateTimeField()),
                ('major', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subscriber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('url', models.TextField(unique=True)),
                ('additional_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'url_table',
                'managed': False,
            },
        ),
    ]
