# Generated by Django 4.0.1 on 2022-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_name', models.TextField()),
                ('date', models.DateTimeField()),
                ('preview_text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('local_path', models.TextField(unique=True)),
                ('url', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
    ]
